### ISSUE TITLE
long command output in remote engine hangs browser

### ISSUE THREAD

**Issue by rdirocco** [amonapp/amon-issues#19]
Example, execution of a wget -O /dev/null http://some_large_file will result in verbose wget output with huge number of lines. This basically hangs the entire browser session, logging out and back in has no impact, once you click on the remote engine window, it triggers the browser behavior again.

This was replicated in chrome and ff 

- Can engine output be purged or trimmed?
- Can long output be truncated and only displayed if requested?

**Comment by martinrusev** [comment]
@rdirocco The second option could be the easier option to implement. Will have a look, I haven't really optimized for long output
