### ISSUE TITLE
Option to grant/deny remote engine rights to a user

### ISSUE THREAD

**Issue by rdirocco** [amonapp/amon-issues#20]
at present all users have the rights for the remote engine if enabled. 

A role based ACL would be ideal in providing a more granular level of control to team members that could be limited to only view access for reporting / response to events and more advanced options for resolution to qualified/granted team members.

**Comment by martinrusev** [comment]
@rdirocco Implementing a better ACL in Amon has been in my todo list for a very long time, but the earliest I can work on that would probably be - end of the summer.
