### ISSUE TITLE
Login "Remember Me"

### ISSUE THREAD

**Issue by thierrybb** [amonapp/amon-issues#23]
Is there normal that the option "Remember Me" on login doesn't remember me so long? I mean, I need to re-log every day, and I still check the "Remember Me" option every time!

Is it possible to keep sign-in for like 30 days?

Thanks

**Comment by martinrusev** [comment]
Hi @thierrybb, 

It is possible. Will look into it. 
The current implementation is something very simple::

```
if not remember_me:
			settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = True
		else:
			settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
```

**Comment by thierrybb** [comment]
Yes I'm not logout on browser close, but I'm logout when I came back to the site like 1 days later.

That not a long retention period for a "Remember me" option!

**Comment by martinrusev** [comment]
@thierrybb You can change these setting easily on your own. Amon is Django, so the session is configured with a normal Django settings file, which can be found in `/opt/amon/amon/settings.py`, you can change this one: `SESSION_COOKIE_AGE = 86400` which is the default, it is in seconds and that is 24 hours.

**Comment by thierrybb** [comment]
That exactly what I'm looking for! Thanks @martinrusev, I will do it!
